//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreCine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cine
    {
        public Cine()
        {
            this.CinePelicula = new HashSet<CinePelicula>();
            this.Sala = new HashSet<Sala>();
        }
    
        public int CodCine { get; set; }
        public string NombreCine { get; set; }
        public string Direccion { get; set; }
    
        public virtual ICollection<CinePelicula> CinePelicula { get; set; }
        public virtual ICollection<Sala> Sala { get; set; }
    }
}
