//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreCine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Director
    {
        public Director()
        {
            this.Pelicula = new HashSet<Pelicula>();
        }
    
        public int CodDirector { get; set; }
        public string NombreDirector { get; set; }
    
        public virtual ICollection<Pelicula> Pelicula { get; set; }
    }
}
