//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreCine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcion
    {
        public Funcion()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int CodFuncion { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public Nullable<System.DateTime> HoraFin { get; set; }
        public Nullable<int> CodPelicula { get; set; }
        public Nullable<System.DateTime> FechaFuncion { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual Pelicula Pelicula { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
