//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreCine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interprete
    {
        public Interprete()
        {
            this.Protagonista = new HashSet<Protagonista>();
        }
    
        public int CodInterprete { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string Nombres { get; set; }
        public string Nacionalidad { get; set; }
        public string Foto { get; set; }
        public string Bio { get; set; }
    
        public virtual ICollection<Protagonista> Protagonista { get; set; }
    }
}
