//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreCine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public Pelicula()
        {
            this.CinePelicula = new HashSet<CinePelicula>();
            this.Funcion = new HashSet<Funcion>();
            this.Protagonista = new HashSet<Protagonista>();
        }
    
        public int CodPelicula { get; set; }
        public string NombrePelicula { get; set; }
        public string Duracion { get; set; }
        public Nullable<System.DateTime> FechaEstreno { get; set; }
        public Nullable<int> CodDirector { get; set; }
    
        public virtual ICollection<CinePelicula> CinePelicula { get; set; }
        public virtual Director Director { get; set; }
        public virtual ICollection<Funcion> Funcion { get; set; }
        public virtual ICollection<Protagonista> Protagonista { get; set; }
    }
}
